name: Build Windows EXE

on:
  push:
    tags: [ 'v*' ]   # build only when you create a tag like v1.0.0
  workflow_dispatch: # …or run manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8 with MAUI
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        # install maui workload
        dotnet-quality: ga
    - run: dotnet workload install maui

    - name: Publish self-contained exe
      run: |
        dotnet publish GarysPawnDesktop.csproj `
          -c Release `
          -f net8.0-windows10.0.19041.0 `
          -r win-x64 `
          -p:WindowsPackageType=None `
          -p:PublishSingleFile=true `
          -p:SelfContained=true `
          -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GarysPawnDesktop-win-x64
        path: publish/GarysPawnDesktop.exe

    - name: Attach EXE to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: publish/GarysPawnDesktop.exe
