name: Build Windows EXEs

on:
  workflow_dispatch:        # run manually
  push:
    tags: [ 'v*' ]          # run automatically on tags like v1.1.0

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [ win-x64, win-x86 ]   # ← both bitnesses
    name: Publish ${{ matrix.arch }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install .NET 8 + MAUI workload
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet workload install maui

    - name: Publish self-contained single-file
      run: |
        dotnet publish GarysPawnDesktop.csproj ^
          -c Release ^
          -f net8.0-windows10.0.19041.0 ^
          -r ${{ matrix.arch }} ^
          -p:PublishSingleFile=true ^
          -p:SelfContained=true ^
          -p:WindowsPackageType=None ^
          -o publish-${{ matrix.arch }}

    # ───────────  make artifacts downloadable from the run  ────────────
    - name: Upload ${{ matrix.arch }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: GarysPawnDesktop-${{ matrix.arch }}
        path: publish-${{ matrix.arch }}/GarysPawnDesktop.exe

    # ───────────  attach EXEs to a Release when run on a tag  ──────────
    - name: Attach EXE to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: publish-${{ matrix.arch }}/GarysPawnDesktop.exe
